export default {
  POINT_FILLCOLOR: '#095268',
  POINT_FILLCOLOR_IMP: '#552A2A',
  POINT_FILLCOLOR_FINISH: '#2B594A',
  POINT_FILLCOLOR_INPROGRESS: '#74B3A9',
  POINT_FILLCOLOR_IMP_FINISH: '#294C3A',
  POINT_FILLCOLOR_IMP_INPROGRESS: '#524A30',

  POINT_STROKECOLOR: '#00CFFF',
  POINT_STROKECOLOR_IMP: '#FD4C4C',
  POINT_STROKECOLOR_FINISH: '#74D3A9',
  POINT_STROKECOLOR_INPROGRESS: '#F9C784',
  POINT_STROKECOLOR_IMP_FINISH: '#10DE71',
  POINT_STROKECOLOR_IMP_INPROGRESS: '#F1B90E',

  POINT_FONTCOLOR: '#00CBFB',
  POINT_FONTCOLOR_IMP: '#e64747',
  POINT_FONTCOLOR_FINISH: '#74D3A9',
  POINT_FONTCOLOR_INPROGRESS: '#F9C784',
  POINT_FONTCOLOR_IMP_FINISH: '#10DE71',
  POINT_FONTCOLOR_IMP_INPROGRESS: '#F1B90E',

  LINE_STROKECOLOR: '#00CFFF',
  LINE_STROKECOLOR_IMP: '#FD4C4C',
  LINE_STROKECOLOR_FINISH: '#74D3A9',
  LINE_STROKECOLOR_INPROGRESS: '#F9C784',
  LINE_STROKECOLOR_IMP_FINISH: '#10DE71',
  LINE_STROKECOLOR_IMP_INPROGRESS: '#F1B90E',

  FONTCOLOR: '#C2E2F2',

  FENQU_COLOR_LIST: ['#164454', '#143C5A'],

  BORDER_COLOR: '#7ee5f6',

}
